### ISSUE TITLE
Windows problem

### ISSUE THREAD

**Issue by loongruige** [PhlexPlexico/3SharpView#2]
Hello, I was trying to get the releases of this to work but it keeps telling me I have to install ".NET Core". Clicking the "Yes" button doesn't redirect me anywhere.
Even though I've tried installing .NET and .NET Core from [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.10-windows-x64-installer) and [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-3.1.30-windows-x64-installer), through some reboots, it keeps giving the error message.

Maybe I've installed the wrong version? I would be happy if helped. (My OS is Windows 7 x64)

![image](https://user-images.githubusercontent.com/72699183/199589515-97ab079c-4823-4f96-b110-79ab6f5e75c1.png)

**Comment by PhlexPlexico** [comment]
Heya, it looks like opening this for me as well gives .net core 3.10 which can actually be found [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.30-windows-x64-installer?cid=getdotnetcore) :) after installation it *should* work.

Thanks!

**Comment by loongruige** [comment]
Thank you, it seems to work!
